# Setup
title: Junuk Cha
description: I am a graduate student in a combined Master's and PhD program specializing in Computer Vision and Deep Learning.
url: https://junukcha.github.io
avatar: /profile.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: junukcha
  card: summary
logo: logo.png
social:
  name: Junuk Cha
  links:
    - https://twitter.com/junukcha
    - https://github.com/junukcha
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: JunukCha
  url: https://github.com/junukcha/
  email: jucha@unist.ac.kr

# collections
collections:
  projects:
    output: true